version: '3.8'

services:
  pygoat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - ./:/app
      - pygoat_media:/app/media
    networks:
      - pygoat_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Security scanning services for local development
  trivy:
    image: aquasec/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./security-reports:/reports
    command: 
      - image
      - --format=json
      - --output=/reports/trivy-local.json
      - pygoat:latest
    depends_on:
      - pygoat
    profiles:
      - security

  zap:
    image: owasp/zap2docker-stable
    volumes:
      - ./security-reports:/zap/wrk
    command:
      - zap-baseline.py
      - -t
      - http://pygoat:8000
      - -J
      - /zap/wrk/zap-baseline.json
      - -r
      - /zap/wrk/zap-baseline.html
    depends_on:
      - pygoat
    networks:
      - pygoat_network
    profiles:
      - security

volumes:
  pygoat_media:

networks:
  pygoat_network:
    driver: bridge